#singleinstance, force
#noenv
RegExMatch(A_ScriptDir, ".*(?=\\paths)", mainDir)
CoordMode, Pixel, Screen
CoordMode, Mouse, Screen
#Include ..\lib\pathReference.ahk

; patch by Amraki
; revision by sanji (sir.moxxi) and Flash (drflash55). Also unofficially by Xilenti (xianleigh) and Lizz (lizz44fu)


walkSend("s","Down")
walkSend("a","Down")
walkSleep(1225)
walkSend("a","Up")
walkSleep(2650)
walkSend("s","Up")
collect(1)

walkSend("d","Down")
walkSleep(4050)
walkSend("d","Up")
collect(2)

;back to spawn
reset()
Sleep, 2000

walkSend("d","Down")
walkSleep(350)
jump()
walkSleep(375)
walkSend("w","Down")
walkSleep(350)
jump()
walkSleep(375)
walkSend("d","Up")
walkSleep(125)
jump()
walkSleep(350)
walkSend("w","Up")
walkSleep(100)
walkSend("s","Down")
walkSend("d","Down")
jump()
walkSleep(150)
walkSend("s","Up")
walkSleep(750)
walkSend("d","Up")
collect(3)

walkSend("d","Down")
walkSleep(475)
walkSend("w","	Down")
walkSleep(350)
walkSend("d","Up")
walkSleep(150)
walkSend("w","Up")
collect(4)

reset()
Sleep, 2000

walkSend("w","Down")
walkSend("a","Down")
walkSleep(3800)
walkSend("a","Up")
walkSleep(675)
walkSend("w","Up")
collect(5)

walkSend("a","Down")
walkSleep(777)
; :)
jump()
walkSend("w","Down")
walkSleep(200)
walkSend("w","Up")
walkSend("a","Down")
walkSleep(800)
walkSend("s","Down")
walkSleep(235)
walkSend("s","Up")
walkSleep(1225)
jump()
walkSleep(350)
walkSend("a","Up")
collect(6)

walkSend("a","Down")
walkSleep(2500)
press("s",500)
walkSend("a","Up")
walkSend("s","Down")
walkSleep(100)
jump()
walkSleep(800)
walkSend("a","Down")
walkSleep(400)
jump()
walkSleep(200)
walkSend("a","Up")
walkSend("s","Down")
walkSleep(200)
jump()
walkSleep(800)
jump()
walkSleep(600)
jump()
walkSleep(800)
jump()
walkSleep(200)
walkSend("s","Up")
walkSend("d","Down")
walksleep(100)
walkSend("d","Up")
sleep, 100
collect(7)